name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js (if you have JS dependencies)
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: bsce22009
          token: ${{ secrets.SONAR_TOKEN }}
