name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.organization=bsce22009
            -Dsonar.projectKey=bsce22009_LPR_ML_Project
            -Dsonar.sources=.
            -Dsonar.inclusions=**/*.html,**/*.css,**/*.js
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN_2 }}
